### ISSUE TITLE
Installing the package fails due to pnpm not being installed

### ISSUE THREAD

**Issue by simondean** [deanc/kysely-schema-generator#1]
Hi.  Attempting to install the package without `pnpm` being available fails with this error:

```
npm ERR! command failed
npm ERR! command sh -c pnpm build
npm ERR! sh: pnpm: command not found
```

**Comment by deanc** [comment]
Thanks @simondean - this should be a small change to use npm I guess instead? Would you like to make a small PR for that?

**Comment by deanc** [comment]
Should be fixed now.
